"""
Auto-generated by the TensorScript transpiler from `optimize DPOModel as DPOStage`.
Target stack: transformers + peft + datasets + accelerate + wandb.
This file is generated — edit the .tensor source and re-transpile rather
than hand-editing this output.
"""
import os
import random
import copy
import torch
from datasets import load_dataset, interleave_datasets
from transformers import (
    AutoModelForCausalLM, AutoConfig, AutoTokenizer, BitsAndBytesConfig,
    TrainingArguments, Trainer, TrainerCallback, set_seed,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

try:
    import wandb
except ImportError:
    wandb = None

OUTPUT_DIR = os.environ.get("TENSORSCRIPT_OUTPUT_DIR", "./output/DPOStage")
RESOLVED_BASE_CHECKPOINT = os.environ.get("TENSORSCRIPT_BASE_CHECKPOINT")  # set by pipeline driver for stage 2+

os.environ['WANDB_PROJECT'] = "pioneer-space/sft-dpo-pipeline"
SEED = random.randint(0, 2**31 - 1)
set_seed(SEED)
print(f'[tensorscript] no seed declared — generated SEED={SEED}, logging for reproducibility')
wandb.config.update({'tensorscript_generated_seed': SEED})
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=1,
    learning_rate=5e-06,
    warmup_steps=200,
    lr_scheduler_type='cosine',
    save_strategy="steps",
    save_steps=20,
    report_to=['wandb'],
    seed=SEED,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_checkpointing=True,
    bf16=False,
    fp16=True,
    load_best_model_at_end=True,
    metric_for_best_model="loss",
    greater_is_better=False,
    eval_strategy="steps",
)
# hardware: block declares static topology — apply via `accelerate config` / launch flags, not in-script:
#   nodes: None, gpus_per_node: None, strategy: None

# ---- dataset ----
raw_dataset = load_dataset("Anthropic/hh-rlhf", split='train', token=None)
_split = raw_dataset.train_test_split(train_size=0.9)
train_dataset = _split['train']
eval_dataset = _split['test']
SEQUENCE_LENGTH = 1024

tokenizer_call = None  # placeholder — actual tokenizer instantiation below
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3-8B")
if tokenizer is not None and tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def _tokenize_fn(batch):
    out = tokenizer(batch.get("text", batch.get("chosen", [""])), truncation=True, max_length=SEQUENCE_LENGTH, padding="max_length")
    out["labels"] = out["input_ids"].copy()
    return out

if tokenizer is not None:
    train_dataset = train_dataset.map(_tokenize_fn, batched=True)
    if eval_dataset is not None:
        eval_dataset = eval_dataset.map(_tokenize_fn, batched=True)

# ---- model ----
_base_path = RESOLVED_BASE_CHECKPOINT
_bnb_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16)
model = AutoModelForCausalLM.from_pretrained(_base_path, quantization_config=_bnb_config, device_map='auto', torch_dtype=torch.float16, attn_implementation='eager')
_lora_config = LoraConfig(r=16, lora_alpha=32, target_modules="all-linear", task_type='CAUSAL_LM')
model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, _lora_config)


class GuardrailCallback(TrainerCallback):
    """Auto-generated from the TensorScript guardrails: list.
    Evaluates all rules each step, in declaration order, against the
    latest logged metrics. terminate_early short-circuits remaining
    rules for that step. Multiple LR-scaling triggers in one step
    compose multiplicatively rather than overwriting each other.
    rollback_and_scale_lr performs a genuine in-place weight restore
    from the most recent on_save snapshot, once one exists."""

    RULES = [   {   'action': {'args': [{'key': None, 'value': 0.3}], 'call': 'rollback_and_scale_lr'},
            'block': None,
            'duration_steps': None,
            'epsilon': None,
            'metric': 'reward_margin',
            'op': '<',
            'value': 0},
        {   'action': {'args': [{'key': None, 'value': 0.5}], 'call': 'rollback_and_scale_lr'},
            'block': None,
            'duration_steps': None,
            'epsilon': None,
            'metric': 'kl_divergence',
            'op': '>',
            'value': 10}]

    def __init__(self):
        self._metric_history = {}
        self._consecutive_true = {}
        self._has_checkpoint = False
        self._last_checkpoint_state = None

    def on_save(self, args, state, control, **kwargs):
        # Called by Trainer right after it writes a checkpoint to disk.
        # We keep our own in-memory copy so rollback doesn't require a
        # disk read (and works even if save_strategy hasn't fired yet
        # for reasons outside the guardrail's control).
        model = kwargs.get("model")
        if model is not None:
            self._last_checkpoint_state = copy.deepcopy(model.state_dict())
            self._has_checkpoint = True
        return control

    def _flat_lines(self, metric, epsilon, window):
        hist = self._metric_history.get(metric, [])
        if len(hist) < window:
            return False
        recent = hist[-window:]
        variance = sum((x - sum(recent) / len(recent)) ** 2 for x in recent) / len(recent)
        return variance < epsilon

    def on_log(self, args, state, control, logs=None, **kwargs):
        if not logs:
            return control
        for k, v in logs.items():
            if isinstance(v, (int, float)):
                self._metric_history.setdefault(k, []).append(v)

        lr_scale_factor = 1.0
        for rule_idx, rule in enumerate(self.RULES):
            metric = rule["metric"]
            if metric not in logs:
                continue
            triggered = False
            if rule["op"] == "flat_lines":
                window = rule["duration_steps"] or 1
                triggered = self._flat_lines(metric, rule["epsilon"], window)
            else:
                val = logs[metric]
                op = rule["op"]
                threshold = rule["value"]
                triggered = {
                    ">": val > threshold, "<": val < threshold,
                    ">=": val >= threshold, "<=": val <= threshold,
                    "==": val == threshold,
                }.get(op, False)
                if triggered and rule["duration_steps"]:
                    key = (rule_idx, "streak")
                    self._consecutive_true[key] = self._consecutive_true.get(key, 0) + 1
                    triggered = self._consecutive_true[key] >= rule["duration_steps"]
                elif rule["duration_steps"]:
                    self._consecutive_true[(rule_idx, "streak")] = 0

            if not triggered:
                continue

            action = rule["action"]
            action_name = action["call"] if isinstance(action, dict) else action

            if action_name == "terminate_early":
                print(f"[guardrail] {metric} triggered terminate_early at step {state.global_step}")
                control.should_training_stop = True
                break  # short-circuit: terminate_early ends evaluation for this step

            elif action_name == "rollback_and_scale_lr":
                factor = action["args"][0]["value"] if isinstance(action, dict) and action["args"] else 0.5
                if not self._has_checkpoint:
                    print(f"[guardrail] WARNING: rollback_and_scale_lr triggered before any checkpoint exists — scaling LR only, skipping rollback")
                else:
                    print(f"[guardrail] {metric} triggered rollback to last checkpoint")
                    kwargs["model"].load_state_dict(self._last_checkpoint_state)
                lr_scale_factor *= factor  # composes multiplicatively across rules firing this step

            elif action_name == "activate_activation_checkpointing":
                kwargs["model"].gradient_checkpointing_enable()

            elif action_name == "activate_cpu_offloading":
                print(f"[guardrail] {metric} triggered activate_cpu_offloading — configure via accelerate's cpu_offload, not mid-run in this callback")

            elif rule.get("block"):
                for stmt in rule["block"]:
                    if stmt["call"] == "print":
                        msg = stmt["args"][0]["value"] if stmt["args"] else ""
                        print(f"[guardrail block] {msg}")
                    elif stmt["call"] == "activate_activation_checkpointing":
                        kwargs["model"].gradient_checkpointing_enable()
                    elif stmt["call"] == "activate_cpu_offloading":
                        print("[guardrail block] activate_cpu_offloading requested — configure via accelerate")

        if lr_scale_factor != 1.0:
            for pg in kwargs["optimizer"].param_groups:
                pg["lr"] *= lr_scale_factor

        return control


trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    callbacks=[GuardrailCallback()] if True else [],
)

if __name__ == "__main__":
    trainer.train()
    trainer.save_model(OUTPUT_DIR)
    if tokenizer is not None:
        tokenizer.save_pretrained(OUTPUT_DIR)
